# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "clients.baml": "client<llm> DefaultClient {\n  provider anthropic\n  options {\n    model \"claude-sonnet-4-20250514\"\n    temperature 0\n  }\n}\n",
    "generators.baml": "// This helps use auto generate libraries you can use in the language of\n// your choice. You can have multiple generators if you use multiple languages.\n// Just ensure that the output_dir is different for each generator.\ngenerator target {\n    // Valid values: \"python/pydantic\", \"typescript\", \"go\", \"rust\", \"ruby/sorbet\", \"rest/openapi\"\n    output_type \"python/pydantic\"\n\n    // Where the generated code will be saved (relative to baml_src/)\n    output_dir \"../\"\n\n    // The version of the BAML package you have installed (e.g. same version as your baml-py or @boundaryml/baml).\n    // The BAML VSCode extension version should also match this version.\n    version \"0.223.0\"\n\n    // Valid values: \"sync\", \"async\"\n    // This controls what `b.FunctionName()` will be (sync or async).\n    default_client_mode sync\n}\n",
    "ocr.baml": "class OcrPageResult {\n  page_number int\n  raw_text string\n}\n\nclass SchemaField {\n  field_name string\n  value string?\n  confidence float\n}\n\nfunction ExtractOcrBatch(page_images: image[]) -> OcrPageResult[] {\n  client DefaultClient\n  prompt #\"\n    Transcribe each of the following document page images exactly as\n    written, preserving mixed Bangla and English text. For each page,\n    return its raw text.\n\n    {{ ctx.output_format }}\n  \"#\n}\n\nfunction FillSchema(document_text: string) -> SchemaField[] {\n  client DefaultClient\n  prompt #\"\n    Extract the fixed set of schema fields from the following document\n    text. For each field, return its value (or null if not found) and a\n    confidence score between 0 and 1.\n\n    Document text:\n    ---\n    {{ document_text }}\n    ---\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
}

def get_baml_files():
    return _file_map