# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractOcrBatch(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.OcrPageResult"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractOcrBatch", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.OcrPageResult"], __result__)

    def FillSchema(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.SchemaField"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FillSchema", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.SchemaField"], __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractOcrBatch(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.OcrPageResult"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractOcrBatch", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.OcrPageResult"], __result__)

    def FillSchema(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.SchemaField"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FillSchema", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.SchemaField"], __result__)

    