# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.FieldValue": types.FieldValue,
    "stream_types.FieldValue": stream_types.FieldValue,

    "types.LandRecordFields": types.LandRecordFields,
    "stream_types.LandRecordFields": stream_types.LandRecordFields,

    "types.ListFieldValue": types.ListFieldValue,
    "stream_types.ListFieldValue": stream_types.ListFieldValue,

    "types.OcrPageResult": types.OcrPageResult,
    "stream_types.OcrPageResult": stream_types.OcrPageResult,


    "types.ConfidenceLevel": types.ConfidenceLevel,

}