# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class ConfidenceLevel(str, Enum):
    LOW = "LOW"
    MED = "MED"
    HIGH = "HIGH"

# #########################################################################
# Generated classes (4)
# #########################################################################

class FieldValue(BaseModel):
    value: typing.Optional[str] = None
    confidence: ConfidenceLevel

class LandRecordFields(BaseModel):
    district: "FieldValue"
    block: "FieldValue"
    mouza: "FieldValue"
    police_station: "FieldValue"
    registry_location: "FieldValue"
    plot_no: "FieldValue"
    deed_no: "FieldValue"
    registration_year: "FieldValue"
    registration_month: "FieldValue"
    registration_day: "FieldValue"
    total_area: "FieldValue"
    land_unit: "FieldValue"
    vendors: "ListFieldValue"
    vendees: "ListFieldValue"
    deed_type: "FieldValue"

class ListFieldValue(BaseModel):
    value: typing.List[str]
    confidence: ConfidenceLevel

class OcrPageResult(BaseModel):
    page_number: int
    raw_text: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
